#Create housing table
-- CREATE TABLE housing (
-- 	id INT,
--     parcel_id VARCHAR(255),
--     acerage VARCHAR (255),
--     land_use VARCHAR(255),
--     property_address VARCHAR(255),
--     sale_date VARCHAR(255),
--     sale_price VARCHAR(255),
--     legal_reference VARCHAR(255),
--     sold_vacant VARCHAR(255),
--     owner_name VARCHAR(255),
--     owner_address VARCHAR(255),
--     tax_dist VARCHAR(255),
--     land_val VARCHAR(255),
--     building_val VARCHAR(255),
--     total_val VARCHAR(255),
--     year_built VARCHAR(255),
--     bedrooms VARCHAR(255),
--     full_bath VARCHAR(255),
--     half_bath VARCHAR(255))
--     
--     SELECT*
--     FROM housing

